version: 2
updates:
  # Enable version updates for Maven dependencies
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "cron"
      cron: "*/5 * * * *"
    open-pull-requests-limit: 10
    reviewers:
      - "priyranjan-K"
    labels:
      - "dependencies"
      - "java"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    rebase-strategy: "auto"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

